### ISSUE TITLE
trafficserver 9.0.0 build failure on OSX big sur

### ISSUE THREAD

**Issue by chenrui333** [apache/trafficserver#7431]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure on macos big sur</summary>

```
libtool: link: /usr/bin/nm -B  unit-tests/.libs/plugin_init_fail_la-plugin_init_fail.o   | sed -n -e 's/^.*[	 ]\([BCDEGRST][BCDEGRST]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /usr/local/Homebrew/Library/Homebrew/shims/mac/super/sed 's/.* //' | sort | uniq > unit-tests/.libs/plugin_init_fail.exp
libtool: link: /usr/bin/grep -E -e "^(TSRemapInit|TSRemapDone|TSRemapDoRemap|TSRemapNewInstance|TSRemapDeleteInstance|TSRemapOSResponse|TSRemapPreConfigReload|TSRemapPostConfigReload|TSPluginInit|pluginDsoVersionTest|getPluginDebugObjectTest)$" "unit-tests/.libs/plugin_init_fail.exp" > "unit-tests/.libs/plugin_init_fail.expT"
Undefined symbols for architecture x86_64:
  "thread-local wrapper routine for pluginThreadContext", referenced from:
      _TSRemapInit in plugin_v1_la-plugin_misc_cb.o
      _TSRemapNewInstance in plugin_v1_la-plugin_misc_cb.o
ld: symbol(s) not found for architecture x86_64
libtool: link: mv -f "unit-tests/.libs/plugin_init_fail.expT" "unit-tests/.libs/plugin_init_fail.exp"
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [unit-tests/plugin_v1.la] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: link: sed -e 's|^|_|' < unit-tests/.libs/plugin_init_fail.exp > unit-tests/.libs/plugin_init_fail-symbols.expsym
libtool: link: clang++  -o unit-tests/.libs/plugin_init_fail.so -bundle  unit-tests/.libs/plugin_init_fail_la-plugin_init_fail.o   -L/usr/local/opt/openssl@1.1/lib -L/usr/local/Cellar/pcre/8.44/lib  -g -O3 -mcx16   -Wl,-exported_symbols_list,unit-tests/.libs/plugin_init_fail-symbols.expsym
Undefined symbols for architecture x86_64:
  "thread-local wrapper routine for pluginThreadContext", referenced from:
      _TSRemapInit in plugin_v2_la-plugin_misc_cb.o
      _TSRemapNewInstance in plugin_v2_la-plugin_misc_cb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [unit-tests/plugin_v2.la] Error 1
libtool: link: ( cd "unit-tests/.libs" && rm -f "plugin_init_fail.la" && ln -s "../plugin_init_fail.la" "plugin_init_fail.la" )
mv -f unit-tests/.deps/plugin_testing_calls_la-plugin_testing_calls.Tpo unit-tests/.deps/plugin_testing_calls_la-plugin_testing_calls.Plo
mv -f unit-tests/.deps/plugin_testing_calls_la-plugin_testing_common.Tpo unit-tests/.deps/plugin_testing_calls_la-plugin_testing_common.Plo
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1718178260
relates to https://github.com/Homebrew/homebrew-core/pull/67323

**Comment by masaori335** [comment]
Seems like `-Wl,-undefined -Wl,dynamic_lookup` is missing.

line 1590 of [1718178260](https://github.com/Homebrew/homebrew-core/runs/1718178260)
```
libtool: link: clang++  -o unit-tests/.libs/plugin_v2.so -bundle  unit-tests/.libs/plugin_v2_la-plugin_misc_cb.o   -L/usr/local/opt/openssl@1.1/lib -L/usr/local/Cellar/pcre/8.44/lib  -g -O3 -mcx16   -Wl,-exported_symbols_list,unit-tests/.libs/plugin_v2-symbols.expsym
```

**Comment by zwoop** [comment]
I think this should be fixed already on the 9.0.x branch, I reverted the issue that causes this failure.

**Comment by carlocab** [comment]
Thanks for the update, @zwoop. Is the fix in the 9.0.1 tag?

**Comment by masaori335** [comment]
@randall #7662 is the new fix for this?

**Comment by carlocab** [comment]
Still getting the same [build errors](https://github.com/Homebrew/homebrew-core/pull/72735/checks?check_run_id=2390599596#step:7:1587) as before with 9.0.1. I tried adding `-undefined dynamic_lookup` to `LDFLAGS`, but it doesn't show up in the call to `clang++` just before the error, so perhaps that's not the way to fix it.

**Comment by bryancall** [comment]
This build issue has been addressed through the migration to CMake. Closing.

If you are still seeing build failures on macOS, please open a new issue with the specific macOS version and build output.
